print('Dwóch policjantów wchodzi do księgarni i pytają:')
print('Czy jest \'Pan Tadeusz\'?')
input()
print('Panie Tadziu, przyszli po pana! - woła ekspedientka')
print()
print('Jak wygląda plaża z lotu ptaka?')
input()
print("O tak: ''''''''''''")
print()
print('Jak się nazywa syn optyka?')
input()
print('Syn', end='')
print('optyk!')
